# Generated by Django 5.2.14 on 2026-05-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Adotante',
                'verbose_name_plural': 'Adotantes',
                'db_table': 'adotante',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('especie', models.CharField(choices=[('cao', 'Cão'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=20, verbose_name='Espécie')),
                ('raca', models.CharField(max_length=100, verbose_name='Raça')),
                ('idade_aproximada', models.PositiveIntegerField(verbose_name='Idade aproximada (anos)')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('femea', 'Fêmea')], max_length=10, verbose_name='Sexo')),
                ('estado_saude', models.TextField(verbose_name='Estado de saúde')),
                ('local_resgate', models.CharField(max_length=200, verbose_name='Local do resgate')),
                ('data_resgate', models.DateField(verbose_name='Data do resgate')),
                ('status', models.CharField(choices=[('resgatado', 'Resgatado'), ('em_tratamento', 'Em tratamento'), ('disponivel', 'Disponível para adoção'), ('adotado', 'Adotado')], default='resgatado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'db_table': 'animal',
                'ordering': ['-data_resgate', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField(verbose_name='Data da adoção')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adocoes', to='gestao.adotante', verbose_name='Adotante')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adocoes', to='gestao.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
                'db_table': 'adocao',
                'ordering': ['-data_adocao'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do tratamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('veterinario', models.CharField(max_length=150, verbose_name='Veterinário')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='gestao.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
                'db_table': 'tratamento',
                'ordering': ['-data'],
            },
        ),
    ]
